FROM lsiobase/xenial-root-armhf

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"

# package versions
ARG NASM_VER="2.13.01"
ARG YASM_VER="1.3.0"

# install build packages
RUN \
 apt-get update && \
 DEBIAN_FRONTEND="noninteractive" apt-get install -y \
	autoconf \
	automake \
	build-essential \
	bzip2 \
	cmake \
	curl \
	gawk \
	gettext \
	git \
	gperf \
	libarchive-dev \
	libbz2-dev \
	libcurl4-gnutls-dev \
	libglib2.0-dev \
	libpcre++-dev \
	libtool \
	lsb-release \
	make \
	mercurial \
	perl \
	pkgconf \
	pkg-config \
	python-dev \
	tar \
	texi2html \
	texinfo \
	unrar \
	unzip \
	wget \
	xz-utils \
	zlib1g-dev && \

# compile nasm
 curl -o \
 /tmp/nasm-${NASM_VER}.tar.xz -L \
	"http://www.nasm.us/pub/nasm/releasebuilds/2.13.01/nasm-${NASM_VER}.tar.xz" && \
 tar xf \
 /tmp/nasm-${NASM_VER}.tar.xz -C /tmp && \
 cd /tmp/nasm-${NASM_VER} && \
 ./configure \
	--prefix=/usr && \
 make && \
 make install && \

# compile yasm
 curl -o \
 /tmp/yasm-${YASM_VER}.tar.gz -L \
	"http://www.tortall.net/projects/yasm/releases/yasm-${YASM_VER}.tar.gz" && \
 tar xf \
 /tmp/yasm-${YASM_VER}.tar.gz -C /tmp && \
 cd /tmp/yasm-${YASM_VER} && \
 sed -i 's#) ytasm.*#)#' Makefile.in && \
 ./configure \
	--prefix=/usr && \
 make && \
 make install && \

# cleanup
 rm -rf \
	/tmp/*
